artifact_location: file:///mnt/c/Users/varin/Desktop/MLAD/CMPT2500_assignment1/src/mlruns/0
creation_time: 1741364501909
experiment_id: '0'
last_update_time: 1741364501909
lifecycle_stage: active
name: Default
